<a href="https://colab.research.google.com/github/the-mir/CNN/blob/main/CNN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import cv2
import os
import random
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
DIRECTORY = r"/content/drive/MyDrive/dataset/leaf"
CATEGORIES = ['Strawberry_fresh', 'Strawberry_scrotch']

In [18]:
data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    label = CATEGORIES.index(category)

    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        img_arr = cv2.imread(img_path)
        img_arr = cv2.resize(img_arr, (100, 100))
        data.append([img_arr, label])

[[[137 127 139]
  [177 167 179]
  [164 154 166]
  ...
  [158 148 160]
  [157 147 159]
  [157 147 159]]

 [[118 108 120]
  [162 152 164]
  [129 119 131]
  ...
  [165 155 167]
  [166 156 168]
  [166 156 168]]

 [[174 164 176]
  [144 134 146]
  [151 141 153]
  ...
  [164 154 166]
  [166 156 168]
  [165 155 167]]

 ...

 [[159 152 159]
  [175 168 175]
  [161 154 161]
  ...
  [175 162 170]
  [174 161 169]
  [176 163 171]]

 [[199 192 199]
  [202 195 202]
  [176 169 176]
  ...
  [172 159 167]
  [171 158 166]
  [174 161 169]]

 [[230 223 230]
  [205 198 205]
  [161 154 161]
  ...
  [174 161 169]
  [173 160 168]
  [176 163 171]]]
[[[198 170 169]
  [196 168 167]
  [195 167 166]
  ...
  [160 136 138]
  [195 171 173]
  [154 130 132]]

 [[196 168 167]
  [194 166 165]
  [193 165 164]
  ...
  [175 151 153]
  [131 107 109]
  [159 135 137]]

 [[196 168 167]
  [194 166 165]
  [193 165 164]
  ...
  [123  99 101]
  [163 139 141]
  [142 118 120]]

 ...

 [[175 147 147]
  [177 149 149]
  [180 152 152]
  ..

In [5]:
data

[[array([[[156, 146, 158],
          [142, 132, 144],
          [134, 124, 136],
          ...,
          [160, 150, 162],
          [162, 152, 164],
          [164, 154, 166]],
  
         [[133, 123, 135],
          [171, 161, 173],
          [152, 142, 154],
          ...,
          [158, 148, 160],
          [161, 151, 163],
          [162, 152, 164]],
  
         [[134, 124, 136],
          [157, 147, 159],
          [127, 117, 129],
          ...,
          [163, 153, 164],
          [163, 153, 165],
          [160, 150, 162]],
  
         ...,
  
         [[151, 144, 151],
          [172, 165, 172],
          [199, 192, 199],
          ...,
          [182, 169, 177],
          [176, 163, 171],
          [180, 167, 175]],
  
         [[174, 167, 174],
          [191, 184, 191],
          [195, 188, 195],
          ...,
          [172, 159, 167],
          [178, 165, 173],
          [175, 162, 170]],
  
         [[203, 196, 203],
          [183, 176, 183],
          [209, 202, 209

In [6]:
random.shuffle(data)

In [7]:
x = []
y = []

for features, label in data:
    x.append(features)
    y.append(label)

X = np.array(x)
Y = np.array(y)
X = X / 255.0

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [9]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=X.shape[1:], activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(2, activation='sigmoid'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=15, validation_split=0.1)

Epoch 1/15
3/3 [==============================] - 5s 1s/step - loss: 0.6763 - accuracy: 0.5444 - val_loss: 0.6713 - val_accuracy: 0.4000
Epoch 2/15
3/3 [==============================] - 2s 688ms/step - loss: 0.6134 - accuracy: 0.7889 - val_loss: 0.5644 - val_accuracy: 0.9000
Epoch 3/15
3/3 [==============================] - 2s 610ms/step - loss: 0.5140 - accuracy: 0.8111 - val_loss: 0.6956 - val_accuracy: 0.4000
Epoch 4/15
3/3 [==============================] - 2s 604ms/step - loss: 0.4976 - accuracy: 0.8000 - val_loss: 0.3697 - val_accuracy: 0.9000
Epoch 5/15
3/3 [==============================] - 2s 598ms/step - loss: 0.4394 - accuracy: 0.8000 - val_loss: 0.5558 - val_accuracy: 0.5000
Epoch 6/15
3/3 [==============================] - 2s 604ms/step - loss: 0.3847 - accuracy: 0.8111 - val_loss: 0.3137 - val_accuracy: 0.9000
Epoch 7/15
3/3 [==============================] - 2s 666ms/step - loss: 0.3552 - accuracy: 0.8333 - val_loss: 0.4174 - val_accuracy: 0.9000
Epoch 8/15
3/3 [=======

In [10]:
split = int(0.8 * len(X))
x_train, x_test = X[:split], X[split:]
y_train, y_test = Y[:split], Y[split:]

In [11]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=15, validation_data=(x_test, y_test))

Epoch 1/15
3/3 [==============================] - 3s 854ms/step - loss: 0.8200 - accuracy: 0.7875 - val_loss: 0.3120 - val_accuracy: 0.9000
Epoch 2/15
3/3 [==============================] - 3s 1s/step - loss: 0.8069 - accuracy: 0.7375 - val_loss: 0.1799 - val_accuracy: 0.9000
Epoch 3/15
3/3 [==============================] - 2s 561ms/step - loss: 0.2963 - accuracy: 0.9000 - val_loss: 0.3323 - val_accuracy: 0.8000
Epoch 4/15
3/3 [==============================] - 2s 696ms/step - loss: 0.3387 - accuracy: 0.8000 - val_loss: 0.2980 - val_accuracy: 0.9000
Epoch 5/15
3/3 [==============================] - 2s 557ms/step - loss: 0.2304 - accuracy: 0.9375 - val_loss: 0.1513 - val_accuracy: 1.0000
Epoch 6/15
3/3 [==============================] - 2s 549ms/step - loss: 0.2140 - accuracy: 0.9250 - val_loss: 0.1741 - val_accuracy: 0.9000
Epoch 7/15
3/3 [==============================] - 2s 546ms/step - loss: 0.2536 - accuracy: 0.8625 - val_loss: 0.1468 - val_accuracy: 0.9500
Epoch 8/15
3/3 [=======

In [12]:
y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred, axis=1)

1/1 [==============================] - 0s 195ms/step


In [13]:
report = classification_report(y_test, y_pred, target_names=CATEGORIES)
print(report)

                    precision    recall  f1-score   support

  Strawberry_fresh       1.00      1.00      1.00        10
Strawberry_scrotch       1.00      1.00      1.00        10

          accuracy                           1.00        20
         macro avg       1.00      1.00      1.00        20
      weighted avg       1.00      1.00      1.00        20



In [14]:
con_m = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(con_m)

Confusion Matrix:
[[10  0]
 [ 0 10]]


In [15]:
img_path = '/content/drive/MyDrive/dataset/leaf/Strawberry_fresh/0b444634-b557-45f4-a68a-8e9e38cd6683___RS_HL 2184.JPG'
img = cv2.imread(img_path)
img = cv2.resize(img, (100, 100))
img = img / 255.0
img = np.expand_dims(img, axis=0)

In [16]:
prediction = model.predict(img)
class_index = np.argmax(prediction)
class_label = CATEGORIES[class_index]
accuracy = prediction[0][class_index] * 100

print("Prediction:", class_label," || Accuracy:", accuracy, "%")

1/1 [==============================] - 0s 37ms/step
Prediction: Strawberry_fresh  || Accuracy: 67.82153844833374 %
